### ISSUE TITLE
Add `config.yml` in issue templates 

### ISSUE THREAD

**Issue by ghost** [bitcoin/bitcoin#21853]
IRC logs:

```

01:53 < wumpus> i think we should add an entry to the "https://github.com/bitcoin/bitcoin/issues/new/choose" list for GUI issues, redirecting people to the appropriate repository
01:59 < michaelfolkson> wumpus: You click on that option and you get "Any report, issue or feature request related to the GUI should be reported at
01:59 < michaelfolkson> https://github.com/bitcoin-core/gui/issues/"
01:59 < wumpus> michaelfolkson: yes, except it should send you to the GUI repo
01:59 < wumpus> oh okay, that's a bit weird but i guess it works
01:59 < michaelfolkson> wumpus: Ah ok I see what you mean
02:01 < michaelfolkson> I agree that would be optimal but not sure if you can be redirected to a different repo when you click a new issue option
02:01 < wumpus> i guess the problem is that "gui" will have the same options, by definition, because it has the same underlying repository
02:01 < michaelfolkson> Right
02:02 < wumpus> i thought it could be like the "view policy" link for security reports, but apparently that one is a special edge cases by github

```

I tried responding in IRC with below example but not sure if people read it because can't even see my messages in logs.

Example of [`config.yml`](https://github.com/prayank23/bitcoin/blob/master/.github/ISSUE_TEMPLATE/config.yml):

```yml
blank_issues_enabled: true
contact_links:
  - name: "\U0001f7e0 An issue or feature request related to the GUI"
    url: https://github.com/bitcoin-core/gui/issues/
    about: The `bitcoin-core/gui` repository is used exclusively for the development of the GUI. Its master branch is identical in all monotree repositories. Release branches and tags do not exist, so please do not fork that repository unless it is for development reasons.
```

![image](https://user-images.githubusercontent.com/13405205/117009072-febbdb80-ad08-11eb-84fd-21c23048ef25.png)

If you click on "open" it will open https://github.com/bitcoin-core/gui/issues in new tab
