### ISSUE TITLE
Always exit silently

### ISSUE THREAD

**Issue by GopherJ** [bitcoin/bitcoin#29783]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

2024-04-02T06:34:52Z dnsseed thread exit
2024-04-02T06:35:53Z Adding fixed seeds as 60 seconds have passed and addrman is empty
2024-04-02T06:35:53Z Added 0 fixed seeds from reachable networks.
2024-04-02T06:36:02Z tor: Thread interrupt
2024-04-02T06:36:02Z Shutdown: In progress...
2024-04-02T06:36:02Z addcon thread exit
2024-04-02T06:36:02Z torcontrol thread exit
2024-04-02T06:36:02Z opencon thread exit
2024-04-02T06:36:02Z net thread exit
2024-04-02T06:36:02Z msghand thread exit
2024-04-02T06:36:02Z DumpAnchors: Flush 0 outbound block-relay-only peer addresses to anchors.dat started
2024-04-02T06:36:02Z DumpAnchors: Flush 0 outbound block-relay-only peer addresses to anchors.dat completed (0.01s)
2024-04-02T06:36:02Z scheduler thread exit
2024-04-02T06:36:02Z Writing 0 unbroadcast transactions to disk.
2024-04-02T06:36:02Z Dumped mempool: 1.47e-06s to copy, 0.00612356s to dump
2024-04-02T06:36:03Z Shutdown: done

### Expected behaviour

At least please give information on why it exited

### Steps to reproduce

docker run ruimarinho/bitcoin-core:latest with the following args:

      - "-regtest=1"
      - "-rpcbind=0.0.0.0:18443"
      - "-rpcuser=devnet"
      - "-rpcpassword=devnet"
      - "-rpcallowip=0.0.0.0/0"
      - "-server=1"
      - "-txindex=1"
      - "-fallbackfee=0.0001"
      - "-zmqpubhashtx=tcp://0.0.0.0:30001"
      - "-zmqpubhashblock=tcp://0.0.0.0:30001"
      - "-prune=0"

### How did you obtain Bitcoin Core

Other

### What version of Bitcoin Core are you using?

sha256:79dd32455cf8c268c63e5d0114cc9882a8857e942b1d17a6b8ec40a6d44e3981

### Operating system and version

Ubuntu 22.04

**Comment by GopherJ** [comment]
example docker-compose:

```
version: '3.7'
services:
  bitcoind:
    image: ruimarinho/bitcoin-core:latest
    ports:
      - 18443:18443
      - 30001:30001
    command:
      - "-regtest=1"
      - "-rpcbind=0.0.0.0:18443"
      - "-rpcuser=devnet"
      - "-rpcpassword=devnet"
      - "-rpcallowip=0.0.0.0/0"
      - "-server=1"
      - "-txindex=1"
      - "-fallbackfee=0.0001"
      - "-zmqpubhashtx=tcp://0.0.0.0:30001"
      - "-zmqpubhashblock=tcp://0.0.0.0:30001"
      - "-prune=0"
    volumes:
      - "./chaindata/bitcoind:/home/bitcoin/.bitcoin"
    networks:
      testing_net:
        ipv4_address: 172.16.238.11
    restart: always

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
```
